plugins {
    id 'java'
    id 'application'
    id 'jacoco'
}

group = 'com.MiguelRocha-24.hero'
version = '1.0-SNAPSHOT'

repositories {
    mavenCentral()
}

dependencies {
    testImplementation platform('org.junit:junit-bom:5.10.0')
    testImplementation 'org.junit.jupiter:junit-jupiter'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
    testImplementation 'org.mockito:mockito-core:5.11.0'
    testImplementation 'org.mockito:mockito-junit-jupiter:5.11.0'
    implementation 'com.googlecode.lanterna:lanterna:3.1.1'
}

application {
    mainClass = 'feup2526.ldts.t02g03.application.App'
}

run {
    standardInput = System.in
}
test {
    useJUnitPlatform()
}

tasks.jacocoTestReport {
    dependsOn tasks.test
    reports {
        xml.required = true
        html.required = true
    }
}